Vue initial interface review
Picovoice/rhino pull request #412
Opened 2022-08-25 19:27 UTC by ErisMik

2022-08-25 19:54 UTC, laves approved these changes

2022-08-25 23:35 UTC, mrrostam approved these changes

2022-08-26 01:15 UTC, ksyeo1010 approved these changes

2022-08-26 01:15 UTC, ksyeo1010 commented on binding/vue/src/rhino.ts
> +    isListeningCallback: (isListening: boolean) => void,
based on what I did on Vue, this types have to be a variable in line 51.

2022-08-29 21:27 UTC, ksyeo1010 approved these changes

2022-08-30 22:21 UTC, laves requested changes

2022-08-30 22:21 UTC, laves commented on binding/vue/README.md
> +- Safari
can you call this section `Browser Compatibility` and add a section called `Framework Compatibility` where you add:
```
- Vue.js 2.6.11+
- Vue.js 3.0.0+
```

2022-08-30 22:21 UTC, laves commented on binding/vue/README.md
> + - `errorCallback` function to catch any error occurred
the wording here makes it sounds like the user has to call them to check:
```suggestion
 - `inferenceCallback` streams inference results from Rhino
 - `contextCallback` function that delivers context info when Rhino has completed initialization
 - `isLoadedCallback` function that executes when Rhino has loaded or unloaded
 - `isListeningCallback` function that executes when Rhino is listening for an inference
 - `errorCallback` function to catch any error occurred
```

2022-08-30 22:21 UTC, laves commented on binding/vue/README.md
> +  keywordDetectionCallback: function(inference) {
```suggestion
  inferenceCallback: function(inference) {
```

2022-08-30 22:21 UTC, laves commented on binding/vue/README.md
> +For example usage refer to our [Web demo application](https://github.com/Picovoice/rhino/tree/master/demo/web).
```suggestion
For example usage, refer to our [Vue demo application](https://github.com/Picovoice/rhino/tree/master/demo/vue).
```

2022-08-30 22:21 UTC, laves commented on binding/vue/src/rhino.ts
> +          contextCallback: (info: string) => void,
I think this should be called contextInfoCallback. All of our other SDKs call the property contextInfo, so this callback should also

2022-08-30 22:21 UTC, laves commented on binding/vue/src/rhino.ts
> +            console.warn("'processErrorCallback' options is not supported, use 'errorCallback' instead.");
can you update this to the message that's used in the other SDKs?

2022-08-30 22:21 UTC, laves commented on demo/vue/README.md
> +# Rhino demo for Rect
```suggestion
# Rhino demo for Vue
```

2022-08-30 22:21 UTC, laves commented on demo/vue/README.md
> +## Compatibility
add note RE: Vue2/Vue3 compatibility (you can copy the one Kwangsoo and I used)

2022-08-31 18:50 UTC, laves requested changes

2022-08-31 18:50 UTC, laves commented on binding/vue/README.md
> +### AccessKey
Duplicate AccessKey section (you may want to double check your other bindings for this)

2022-08-31 19:11 UTC, laves approved these changes

2022-08-31 22:38 UTC, merged