v3.0 go
Picovoice/rhino pull request #589
Opened 2023-10-13 22:58 UTC by ksyeo1010

2023-10-17 22:29 UTC, laves requested changes

2023-10-17 22:29 UTC, laves commented on .github/workflows/go.yml
> +        os: [ubuntu-latest, macos-latest, windows-latest]
not a big deal, but you should tell you editor to trim spaces on save

2023-10-17 22:29 UTC, laves commented on binding/go/rhino.go
> +	}
don't we usually put this in the `if` statement? I know it doesn't change the behaviour, but it does read better

2023-10-17 22:29 UTC, laves commented on binding/go/rhino.go
> +			MessageStack: 	messageStack}
is all this weird spacing Go's formatter? If so, it's fine, I'm just surprised how random it looks at time

2023-10-17 22:29 UTC, laves commented on binding/go/rhino_test.go
> +	"reflect"
format

2023-10-17 22:50 UTC, laves reviewed
there was more than just that one format issue in `rhino.go` - did you run a formatter on the file or just fix the one I pointed out?

2023-10-17 22:53 UTC, ksyeo1010 commented
I ran it but I guess doesnt convert the go tabs into spaces

2023-10-18 21:52 UTC, laves approved these changes

2023-10-18 21:52 UTC, merged